FROM java:8-jre
WORKDIR /usr/src
ADD ./target/RibbonConfiguration-0.0.1-SNAPSHOT.jar /usr/src/RibbonConfiguration-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "RibbonConfiguration-0.0.1-SNAPSHOT.jar"]
