spring:

# --Added By Rabi -Start --- # 
#  data:
#    mongodb:
#       uri: mongodb://${MONGO_HOST}/assignment
      #username: ${MONGO_USERNAME}
      #password: ${MONGO_PASSWORD}
      #database: ${MONGO_DATABASE}
      #port: ${MONGO_PORT}
      #host: ${MONGO_HOST}
  datasource:
     url: jdbc:h2:mem:testdb
     driverClassName: org.h2.Driver
     username: sa
     password: password

# --Added By Rabi -End --- # 
  application:
    name: category-service
server:
  port: ${server-port:9400} 
#      ribbon.listOfServers: localhost:9400
#      ribbon.eureka.enabled: true

#eureka:
#  client :
#   eureka-server-port : 8761