eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
        service-url:
        defaultZone: http://localhost:8761/eureka/
server:  port: 9100

spring:  application:    name: AuthenticationService

jwt:
  security:
    secret: supersecret